version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:18.20.5
    steps:
      - checkout
      - run:
          name: Install HTTP Server
          command: npm install -g http-server
      - run:
          name: Start HTTP Server
          command: http-server -p 8080
workflows:
  version: 2
  build-and-serve:
    jobs:
      - build